// VoitureService.idl
module CobraService {
    
    // Structure pour représenter une voiture
    struct Voiture {
        string nom;
        string marque;
    };
    
    // Séquence (liste) de voitures
    typedef sequence<Voiture> VoitureList;
    
    // Interface du service
    interface VoitureService {
        // Récupère toutes les voitures de la base
        VoitureList getVoitures();
        
        // Ajoute une voiture dans la base
        void ajouterVoiture(in Voiture v);
        
        // Lit les voitures depuis un fichier txt et les envoie à C++ via CORBA
        void lireVoituresDepuisFichier(in string nomFichier);
    };

};
