// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "VoitureService.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
CobraService::Voiture::operator>>= (cdrStream &_n) const
{
  _n.marshalString(nom,0);
  _n.marshalString(marque,0);

}

void
CobraService::Voiture::operator<<= (cdrStream &_n)
{
  nom = _n.unmarshalString(0);
  marque = _n.unmarshalString(0);

}

CobraService::VoitureService_ptr CobraService::VoitureService_Helper::_nil() {
  return ::CobraService::VoitureService::_nil();
}

::CORBA::Boolean CobraService::VoitureService_Helper::is_nil(::CobraService::VoitureService_ptr p) {
  return ::CORBA::is_nil(p);

}

void CobraService::VoitureService_Helper::release(::CobraService::VoitureService_ptr p) {
  ::CORBA::release(p);
}

void CobraService::VoitureService_Helper::marshalObjRef(::CobraService::VoitureService_ptr obj, cdrStream& s) {
  ::CobraService::VoitureService::_marshalObjRef(obj, s);
}

CobraService::VoitureService_ptr CobraService::VoitureService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CobraService::VoitureService::_unmarshalObjRef(s);
}

void CobraService::VoitureService_Helper::duplicate(::CobraService::VoitureService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

CobraService::VoitureService_ptr
CobraService::VoitureService::_duplicate(::CobraService::VoitureService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

CobraService::VoitureService_ptr
CobraService::VoitureService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CobraService::VoitureService_ptr
CobraService::VoitureService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CobraService::VoitureService_ptr
CobraService::VoitureService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_VoitureService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_VoitureService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_VoitureService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CobraService::VoitureService::_PD_repoId = "IDL:CobraService/VoitureService:1.0";


CobraService::_objref_VoitureService::~_objref_VoitureService() {
  
}


CobraService::_objref_VoitureService::_objref_VoitureService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CobraService::VoitureService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
CobraService::_objref_VoitureService::_ptrToObjRef(const char* id)
{
  if (id == ::CobraService::VoitureService::_PD_repoId)
    return (::CobraService::VoitureService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::CobraService::VoitureService::_PD_repoId))
    return (::CobraService::VoitureService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for CobraService::VoitureService::getVoitures

// Proxy call descriptor class. Mangled signature:
//  _cCobraService_mVoitureList
class _0RL_cd_f5cf5122317f7842_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f5cf5122317f7842_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  CobraService::VoitureList_var result;
};

void _0RL_cd_f5cf5122317f7842_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const CobraService::VoitureList&) result >>= _n;

}

void _0RL_cd_f5cf5122317f7842_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new CobraService::VoitureList;
  (CobraService::VoitureList&)result <<= _n;

}

const char* const _0RL_cd_f5cf5122317f7842_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f5cf5122317f7842_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f5cf5122317f7842_00000000* tcd = (_0RL_cd_f5cf5122317f7842_00000000*)cd;
  CobraService::_impl_VoitureService* impl = (CobraService::_impl_VoitureService*) svnt->_ptrToInterface(CobraService::VoitureService::_PD_repoId);
  tcd->result = impl->getVoitures();


}

CobraService::VoitureList* CobraService::_objref_VoitureService::getVoitures()
{
  _0RL_cd_f5cf5122317f7842_00000000 _call_desc(_0RL_lcfn_f5cf5122317f7842_10000000, "getVoitures", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}

CobraService::_pof_VoitureService::~_pof_VoitureService() {}


omniObjRef*
CobraService::_pof_VoitureService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::CobraService::_objref_VoitureService(ior, id);
}


::CORBA::Boolean
CobraService::_pof_VoitureService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::CobraService::VoitureService::_PD_repoId))
    return 1;
  
  return 0;
}

const CobraService::_pof_VoitureService _the_pof_CobraService_mVoitureService;

CobraService::_impl_VoitureService::~_impl_VoitureService() {}


::CORBA::Boolean
CobraService::_impl_VoitureService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getVoitures")) {

    _0RL_cd_f5cf5122317f7842_00000000 _call_desc(_0RL_lcfn_f5cf5122317f7842_10000000, "getVoitures", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
CobraService::_impl_VoitureService::_ptrToInterface(const char* id)
{
  if (id == ::CobraService::VoitureService::_PD_repoId)
    return (::CobraService::_impl_VoitureService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::CobraService::VoitureService::_PD_repoId))
    return (::CobraService::_impl_VoitureService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
CobraService::_impl_VoitureService::_mostDerivedRepoId()
{
  return ::CobraService::VoitureService::_PD_repoId;
}

POA_CobraService::VoitureService::~VoitureService() {}

