// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __VoitureService_hh__
#define __VoitureService_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_VoitureService
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_VoitureService
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_VoitureService
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CobraService

_CORBA_MODULE_BEG

  struct Voiture {
    typedef _CORBA_ConstrType_Variable_Var<Voiture> _var_type;

    
    ::CORBA::String_member nom;

    ::CORBA::String_member marque;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Voiture::_var_type Voiture_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Voiture,Voiture_var > Voiture_out;

  class VoitureList_var;

  class VoitureList : public _CORBA_Unbounded_Sequence< Voiture >  {
  public:
    typedef VoitureList_var _var_type;
    inline VoitureList() {}
    inline VoitureList(const VoitureList& _s)
      : _CORBA_Unbounded_Sequence< Voiture > (_s) {}

    inline VoitureList(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence< Voiture > (_max) {}
    inline VoitureList(_CORBA_ULong _max, _CORBA_ULong _len, Voiture* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence< Voiture > (_max, _len, _val, _rel) {}

  

    inline VoitureList& operator = (const VoitureList& _s) {
      _CORBA_Unbounded_Sequence< Voiture > ::operator=(_s);
      return *this;
    }
  };

  class VoitureList_out;

  class VoitureList_var {
  public:
    inline VoitureList_var() : _pd_seq(0) {}
    inline VoitureList_var(VoitureList* _s) : _pd_seq(_s) {}
    inline VoitureList_var(const VoitureList_var& _s) {
      if (_s._pd_seq)  _pd_seq = new VoitureList(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~VoitureList_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline VoitureList_var& operator = (VoitureList* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline VoitureList_var& operator = (const VoitureList_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new VoitureList;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline Voiture& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline VoitureList* operator -> () { return _pd_seq; }
    inline const VoitureList* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator VoitureList& () const { return *_pd_seq; }
#else
    inline operator const VoitureList& () const { return *_pd_seq; }
    inline operator VoitureList& () { return *_pd_seq; }
#endif
      
    inline const VoitureList& in() const { return *_pd_seq; }
    inline VoitureList&       inout()    { return *_pd_seq; }
    inline VoitureList*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline VoitureList* _retn() { VoitureList* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class VoitureList_out;
    
  private:
    VoitureList* _pd_seq;
  };

  class VoitureList_out {
  public:
    inline VoitureList_out(VoitureList*& _s) : _data(_s) { _data = 0; }
    inline VoitureList_out(VoitureList_var& _s)
      : _data(_s._pd_seq) { _s = (VoitureList*) 0; }
    inline VoitureList_out(const VoitureList_out& _s) : _data(_s._data) {}
    inline VoitureList_out& operator = (const VoitureList_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline VoitureList_out& operator = (VoitureList* _s) {
      _data = _s;
      return *this;
    }
    inline operator VoitureList*&()  { return _data; }
    inline VoitureList*& ptr()       { return _data; }
    inline VoitureList* operator->() { return _data; }

    inline Voiture& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    VoitureList*& _data;

  private:
    VoitureList_out();
    VoitureList_out& operator=(const VoitureList_var&);
  };

#ifndef __CobraService_mVoitureService__
#define __CobraService_mVoitureService__
  class VoitureService;
  class _objref_VoitureService;
  class _impl_VoitureService;
  
  typedef _objref_VoitureService* VoitureService_ptr;
  typedef VoitureService_ptr VoitureServiceRef;

  class VoitureService_Helper {
  public:
    typedef VoitureService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_VoitureService, VoitureService_Helper> VoitureService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_VoitureService,VoitureService_Helper > VoitureService_out;

#endif

  // interface VoitureService
  class VoitureService {
  public:
    // Declarations for this interface type.
    typedef VoitureService_ptr _ptr_type;
    typedef VoitureService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_VoitureService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    VoitureList* getVoitures();
    void ajouterVoiture(const ::CobraService::Voiture& v);
    void lireVoituresDepuisFichier(const char* nomFichier);

    // Constructors
    inline _objref_VoitureService()  { _PR_setobj(0); }  // nil
    _objref_VoitureService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_VoitureService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_VoitureService(const _objref_VoitureService&);
    _objref_VoitureService& operator = (const _objref_VoitureService&);
    // not implemented

    friend class VoitureService;
  };

  class _pof_VoitureService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_VoitureService() : _OMNI_NS(proxyObjectFactory)(VoitureService::_PD_repoId) {}
    virtual ~_pof_VoitureService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_VoitureService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_VoitureService();

    virtual VoitureList* getVoitures() = 0;
    virtual void ajouterVoiture(const ::CobraService::Voiture& v) = 0;
    virtual void lireVoituresDepuisFichier(const char* nomFichier) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CobraService
_CORBA_MODULE_BEG

  class VoitureService :
    public virtual CobraService::_impl_VoitureService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~VoitureService();

    inline ::CobraService::VoitureService_ptr _this() {
      return (::CobraService::VoitureService_ptr) _do_this(::CobraService::VoitureService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CobraService
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CobraService::VoitureService::_marshalObjRef(::CobraService::VoitureService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_VoitureService
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_VoitureService
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_VoitureService
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_VoitureService
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_VoitureService
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_VoitureService
#endif

#endif  // __VoitureService_hh__

